-- D1 schema for the Cloudflare Worker (board + small settings).
CREATE TABLE IF NOT EXISTS items (id TEXT PRIMARY KEY, data TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS searches (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS analyses (k TEXT PRIMARY KEY, v TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS media (k TEXT PRIMARY KEY, type TEXT NOT NULL, data BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS users (email TEXT PRIMARY KEY, name TEXT, at INTEGER NOT NULL, blocked INTEGER NOT NULL DEFAULT 0, seen INTEGER);
-- existing databases: ALTER TABLE users ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0; ALTER TABLE users ADD COLUMN seen INTEGER;
